# Generated by Django 4.1.3 on 2022-12-15 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0007_delete_wreath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realwreath',
            name='orn1',
            field=models.CharField(default=-1, max_length=200),
        ),
        migrations.AlterField(
            model_name='realwreath',
            name='orn2',
            field=models.CharField(default=-1, max_length=200),
        ),
        migrations.AlterField(
            model_name='realwreath',
            name='orn3',
            field=models.CharField(default=-1, max_length=200),
        ),
        migrations.AlterField(
            model_name='realwreath',
            name='orn4',
            field=models.CharField(default=-1, max_length=200),
        ),
        migrations.AlterField(
            model_name='realwreath',
            name='orn5',
            field=models.CharField(default=-1, max_length=200),
        ),
        migrations.AlterField(
            model_name='realwreath',
            name='orn6',
            field=models.CharField(default=-1, max_length=200),
        ),
        migrations.AlterField(
            model_name='realwreath',
            name='orn7',
            field=models.CharField(default=-1, max_length=200),
        ),
        migrations.AlterField(
            model_name='sock',
            name='sock1_img',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sock',
            name='sock1_name',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sock',
            name='sock2_img',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sock',
            name='sock2_name',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sock',
            name='sock3_img',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sock',
            name='sock3_name',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
